### PR TITLE
Hydrate fieldnames for embedded entities

### PR DESCRIPTION
**Pull request by prolic**
If you need addtional tests, let me know.

### CODE REVIEW

**Comment by gianarb** [comment]
Hi @prolic can you add tests for this improvement? Thanks

**Comment by prolic** [comment]
No problem, please give me a few days. I should have it done until weekend. Currently very busy ;)

**Comment by gianarb** [comment]
No problem! :) Thanks

**Comment by Bilge** [comment]
How can it be adequate to just check if the field name contains a `.`? Surely this would break if I create a field with a dot in its name.

I would expect it to be necessary to check the metadata and verify that this field is in fact an embedded entity. I also expect to see explicit support for [column prefixing](http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html#column-prefixing) including no column prefixes.

Does this PR really address all these issues?

**Comment by prolic** [comment]
Thx @Bilge I will take this into consideration when updating this PR.

**Comment by prolic** [comment]
I added tests for extration of embedded entities. I try to come up with additional tests for hydration tomorrow.

**Comment by prolic** [comment]
solves extration of: https://github.com/doctrine/DoctrineModule/issues/496

**Comment by gianarb** [comment]
Thanks! :)

**Comment by prolic** [comment]
Classmetadata is handled differently by Doctrine ORM and Doctrine ODM (MongoDB). I will switch to https://github.com/phpro/zf-doctrine-hydration-module for now.

**Comment by Bilge** [comment]
u whot

**Pull request closed without merging**
