### PR TITLE
Added PredisCache support.

### PR DESCRIPTION
**Pull request by Bilge**

### CODE REVIEW

**Comment by Bilge** [comment]
Obviously the build will fail on 5.3 but I'm also expecting my other PR (#491) to be merged.

**Comment by Bilge** [comment]
@gianarb How about getting this merged also?

**Comment by gianarb** [comment]
Thanks for this feature. In this moment we are working to push out the door 0.8.1 and 0.9.0 release.. Maybe this PRs is ready for 0.9.0 :)

**Comment by Bilge** [comment]
@gianarb Why does it need to wait? It's a new feature with no BC breaks.

**Comment by gianarb** [comment]
Thanks 49f409f04e21a47a2517b1eb92841153d88d0ef0

**Pull request closed without merging**
