### PR TITLE
Objects Selection Identifiers (ToMany)

### PR DESCRIPTION
**Pull request by nastron**
Changing the object selection strategy in the toMany function so it only fetches based on the identifiers ignoring any other sent params (if any).

### CODE REVIEW

**Comment by gianarb** [comment]
Hi @nastron have you news for this PR? :)
Thanks!

**Comment by gianarb** [comment]
I close it for inactivity

**Comment by fabioginzel** [comment]
+1 I need this...

**Comment by nastron** [comment]
Hi @gianarb,

This was obviously closed due to inactivity. Can you please elaborate on how specific a test case for this needs to be?

I would love to have this PR merged in since I'm going to need it available in production on my next dependency update, and possibly other devs need it too.

Thanks!

**Comment by fabioginzel** [comment]
Thanks @gianarb I've created a workaround, posting PK with "0" (zero)

**Comment by fabioginzel** [comment]
My workaround don't work :(

**Pull request closed without merging**
