### PR TITLE
Feature/form element data attributes support

### PR DESCRIPTION
**Pull request by manuakasam**
Refactored the given implementation of `option_attributes` to allow for more use-cases and be more handy.

References #504

### CODE REVIEW

**Comment by manuakasam** [comment]
git is hard Xx

**Comment by gianarb** [comment]
ahahah :D :D :dragon_face:

**Comment by gianarb** [comment]
Hi @manuakasam can you add into the UPDATE.md a new paragraph `1.0.0` and you can write this improvement? 

Thanks!

**Comment by gianarb** [comment]
This is not a BC Break! :P Sorry

**Comment by gianarb** [comment]
Thanks @manuakasam

**Comment by manuakasam** [comment]
\o/ likewise

**Comment by gianarb** [comment]
:palm_tree:

**Pull request merged**
