### PR TITLE
Allow doctrine/persistence 3

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by driehle** [comment]
Looks good to me, but CI now runs persistence 2 only with PHP 7.4. Maybe we should have `dependencies=lowest` running with all supported PHP versions?

**Comment by snapshotpl** [comment]
@driehle done

**Review by driehle — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by snapshotpl** [comment]
Is there any blocker to merge and release?

**Comment by snapshotpl** [comment]
Thanks. What about release?

**Comment by greg0ire** [comment]
I'll defer to @driehle for the release.

**Comment by driehle** [comment]
I was thinking about including some changes related to doctrine/cache in 5.2.0, but didn't find any time to look into this so far. So let's go with 5.2.0 as it is for now. We can make a 5.3.0 later then.

**Pull request merged**
