### PR TITLE
Updated upstream workflows

### PR DESCRIPTION
**Pull request by driehle**

### CODE REVIEW

**Comment by derrabus** [comment]
This PR should target the 4.4.x branch, shouldn't it?

**Comment by greg0ire** [comment]
Yes, but it won't have any effect on releases until merged up into 5.0.x

**Comment by driehle** [comment]
I targeted it on 5.0.x as there are currently no plans on making another 4.4.x release. Nevertheless, we can push it to 4.4.x and make a manual merge up, just in case.

**Comment by driehle** [comment]
Rebased on 4.4.x

**Review by greg0ire — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by driehle** [comment]
Merge-up to 5.0.x done

**Pull request merged**
