### PR TITLE
Fix ZendStorageCache::doSave with lifetime

### PR DESCRIPTION
**Pull request by seyfer**
https://github.com/doctrine/DoctrineModule/issues/484

### CODE REVIEW

**Comment by seyfer** [comment]
I added posibility to use ttl from zend cache config for ZendStorageCache.

It's added because Zend cache config have some default ttl time that configured in cache.local.php (or anywhere). If I provide custom ttl it use this value as expiration time, if I provide 0 (default) it sets infinite lifetime. 
And if Zend cache driver used for Doctrine caching I want to use configured in Zend config lifetime. 
So I added a case for -1 value. In this case configured Zend cache value will be used.

For better explanation there is an example:
```
$cache->save($cacheItemKey, $items, 20); // save item to cache
$cache->save($cacheItemKey . "_ne", $items, 0); // save item to cache not expire
$cache->save($cacheItemKey . "_d", $items, -1); // save item to cache with default ttl
```

And if `$cacheItemKey` has value `sites` we will have 3 keys in redis (memcached, etc) storage.
sites - expire in 20 seconds
sites_ne - not expired key
sites_d - use ttl from config

Logic implemented with static properties in `ZendStorageCache`. Because if we change `$this->storage` ttl first time it will be saved in object. So we need save what ttl value was in `$this->storage` before change it. I'm not found possibility to access value from config in another way while in `ZendStorageCache` context.
Than we use this saved default value if lifetime parameter passed with -1 value.

**Comment by gianarb** [comment]
Thanks!

**Comment by gianarb** [comment]
@seyfer can you help me to check this feedback in this PR? [399#issuecomment-73426061](https://github.com/doctrine/DoctrineModule/pull/399#issuecomment-73426061)
What do you think?

**Comment by gianarb** [comment]
Hello @seyfer can we address this? 
Thanks a lot

**Comment by TomHAnderson** [comment]
Closing due to lack of action.

**Pull request closed without merging**
