### PR TITLE
Fixed use statements to alphabetical order

### PR DESCRIPTION
**Pull request by TomHAnderson**

### CODE REVIEW

**Comment by TomHAnderson** [comment]
I don't know if it's using a merge up strategy either.  Google doesn't know and this is the closest I found:  https://git-scm.com/docs/merge-strategies  

If you think it's important to know can you please explain what you mean?

**Comment by greg0ire** [comment]
> If you think it's important to know can you please explain what you mean?

Sure. Right now, there are several branches on this repository: master, 1.0.x, 1.1.x etc.
Your changes are relevant for probably more than just `master`. My question is: in such cases, how do the change land on another branch. FYI, Doctrine used to use a merge on master + cherry-pick on lower branches strategy, and is trying to switch to a merge on the lowest relevant branch, then merge up on the next branch above that one, and so on.

**Comment by TomHAnderson** [comment]
This branch was targeted to merge to `develop`.  Once I'm satisfied DoctrineORMModule and api-tools-doctrine-querybuilder-orm are working then I'll merge develop to master.  Does that solve your concern?

**Comment by greg0ire** [comment]
I just noticed that the latest release number starts with a 3, so I guess all the branches I'm worrying about are no longer maintained. So concern solved, sorry for the disturbance, I'm new :)

**Comment by TomHAnderson** [comment]
Gaphah.  Your goofy mug is all over phpland.  Glad to have your critique!

**Pull request merged**
