### PR TITLE
Add laminas-servicemanager v4 support

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/doctrine/DoctrineORMModule/pull/754

### CODE REVIEW

**Comment by samsonasik** [comment]
Use php 8.3 seems still installing laminas-servicemanager v3, directly use v4 got error:

```
➜  DoctrineModule git:(patch-1) ✗ php82 /usr/local/bin/composer up
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-cache 3.6.0 requires php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.17) does not satisfy that requirement.
    - laminas/laminas-cache[3.7.0, ..., 3.9.1] require laminas/laminas-servicemanager ^3.11.1 -> found laminas/laminas-servicemanager[3.11.1, ..., 3.22.1] but it conflicts with your root composer.json require (^4.0).
    - laminas/laminas-cache[3.10.0, ..., 3.10.1] require laminas/laminas-servicemanager ^3.18.0 -> found laminas/laminas-servicemanager[3.18.0, ..., 3.22.1] but it conflicts with your root composer.json require (^4.0).
    - laminas/laminas-cache[3.11.0, ..., 3.12.1] require laminas/laminas-servicemanager ^3.21 -> found laminas/laminas-servicemanager[3.21.0, 3.22.0, 3.22.1] but it conflicts with your root composer.json require (^4.0).
    - Root composer.json requires laminas/laminas-cache ^3.6.0 -> satisfiable by laminas/laminas-cache[3.6.0, ..., 3.12.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by samsonasik** [comment]
I see, it require https://github.com/laminas/laminas-cache/pull/297

**Comment by samsonasik** [comment]
Ref https://github.com/laminas/laminas-cache/pull/296

**Comment by samsonasik** [comment]
laminas-cache v4 now support laminas-servicemanager v4

**Comment by TomHAnderson** [comment]
Work on updating this library will be tracked here:  https://github.com/doctrine/DoctrineModule/milestone/35

**Pull request closed without merging**
