### PR TITLE
Update doctrine-module.php

### PR DESCRIPTION
**Pull request by Thalles**
After the update, the command line work in ZF3 .

### CODE REVIEW

**Comment by webimpress** [comment]
I did the same in #572

**Comment by exptom** [comment]
You are missing an import of  `Zend\Stdlib\ArrayUtils`

**Comment by webimpress** [comment]
Duplicated. #572

**Comment by Thalles** [comment]
Sorry, I had not seen.
I'm starting now

**Comment by gianarb** [comment]
Hello @Thalles thanks for your work but I close this PR because it's duplicated.

**Pull request closed without merging**
