### PR TITLE
update hydrator with the new available interface/method in doctrine/common

### PR DESCRIPTION
**Pull request by fabiocarneiro**
There is a new interface in https://github.com/doctrine/common/pull/343, this is the implementation that will make possible to work with embeddables in DoctrineObject hydrator through this classmetadata implementation https://github.com/doctrine/doctrine2/pull/1185.

**This modification in composer.json is purposeful and will be removed as soon as/if doctrine/common PR gets merged w/ forced push. The objective is to make it possible to travis test the DoctrineModule with the new interface and show that this pr is dependent from a pr in doctrine/common**

### CODE REVIEW

**Comment by gianarb** [comment]
@fabiocarneiro Thanks for this PR but I close it.
Ping me if this PR change status doctrine/doctrine2#1179 and I reopen :+1:

**Comment by fabiocarneiro** [comment]
@gianarb That PR is discontinued. You should close that one, not this one. This is part of https://github.com/doctrine/common/pull/343 and https://github.com/doctrine/doctrine2/pull/1185

**Comment by gianarb** [comment]
Thanks for your work.. :) we wait a stable situation about it

**Comment by fabiocarneiro** [comment]
@gianarb Reopen it please. Its part of that. It makes no sense to add that interface to Doctrine\Common if this work here is not "available". Its waiting to be reviewed since nov 12. I already bothered @Ocramius  a couple of times since then.

**Comment by gianarb** [comment]
Hi @fabiocarneiro original PR into the doctrine2 repo is closed..

**Comment by fabiocarneiro** [comment]
@gianarb Yes, that was discontinued, so it was closed. This one has a new approach. Read the description please.

**Comment by Ocramius** [comment]
Closing as per doctrine/doctrine2#1185 and doctrine/common#343

**Pull request closed without merging**
