### PR TITLE
Extract hydrators to separate repository

### PR DESCRIPTION
**Pull request by michalbundyra**
I've created repository with the hydrators:
https://github.com/webimpress/doctrine-zend-hydrator

I want to use Doctrine with ZF Expressive application and I need hydrators there. `DoctrineModule` is specific for MVC ZF applications, and I don't want to install all of those dependencies just to use hydrators. I think many other parts we can extract to smaller packages, and make them reusable in Expressive applications.

I am happy to transfer this repository to doctrine project. We can change namespace etc. I didn't publish any release there. I just wanted to create something to start with :)

### CODE REVIEW

**Comment by webimpress** [comment]
@Ocramius what do you think about it? Who can make any decision on it? I'd like to add support for zend-hydrator v3, but I think it would be better to have it in separate repo. Thanks!

**Comment by webimpress** [comment]
Library `webimpress/zend-doctrine-hydrator` updated to the latest changed made in that library. That branch is now rebased to resolve conflicts. It would be nice to move forward with it and add support for zend-hydrator v3.

ping @TomHAnderson

**Comment by snapshotpl** [comment]
ping @TomHAnderson

**Comment by webimpress** [comment]
@TomHAnderson PR is now updated to use [`doctrine/doctrine-zend-hydrator` v1.0.0](https://github.com/doctrine/doctrine-zend-hydrator/releases/tag/1.0.0). 

Not sure if we should throw some E_USER_DEPRECATED notices here?

**Comment by snapshotpl** [comment]
How can I help to move forward?

**Comment by TomHAnderson** [comment]
The next step is to merge support for Zend Hydrator 3.0 into https://github.com/doctrine/doctrine-zend-hydrator  @webimpress and I are in communication and expect a release soon.

**Comment by snapshotpl** [comment]
@michalbundyra @TomHAnderson I can help with this

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/doctrine-laminas-hydrator

**Pull request closed without merging**
