### PR TITLE
Add PHP 8.0 support

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by SenseException** [comment]
Thanks for the contribution.

Before this can be reviewed we need you to

* add a PHP 8 step to `.travis.yml`
* fix the breaking build that is caused by your changes

**Comment by Slamdunk** [comment]
> add a PHP 8 step to `.travis.yml`

Sorry, done, but this morning Travis seems dead

> fix the breaking build that is caused by your changes

Like in the build, I've just:

```
$ php7.2 ~/bin/composer config minimum-stability dev
$ php7.2 ~/bin/composer update
$ php7.2 vendor/bin/phpunit
```

And the tests pass, let's wait for what Travis says now

**Review by SenseException — APPROVED** [review]

**Comment by SenseException** [comment]
I'm not sure if the target branch will stay at 4.1.x or if these changes will be targeting a later branch.

**Comment by driehle** [comment]
@SenseException The current 4.1.1 release is broken anyways as commit f9cf0986ea70655d23e10fbf0d9198cb3e1eda1d is tagged as 4.1.1, though that commit is from the 4.0.x branch. See #720 for a related discussion. Besides, the new features regarding session containers have only been introduced in the 4.0.x branch and have not yet been ported into the 4.1.x branch, which is why I have created #721.

grafik

**Review by TomHAnderson — APPROVED** [review]

**Pull request merged**
